env:
  global:
    - ENCRYPTION_LABEL: "8c7035aad7a2"

install: true

sudo: false

language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

addons:
  apt:
    packages:
      - gnome-themes-standard
      - metacity
      - libwebkit-dev

before_install:
  - openssl aes-256-cbc -K $encrypted_8c7035aad7a2_key -iv $encrypted_8c7035aad7a2_iv
    -in deploy-key.enc -out deploy-key -d
  - chmod 600 deploy-key
  - cp deploy-key ~/.ssh/id_rsa

script:
  - mvn clean verify -e -Dtarget-platform-classifier=eclipse-4.7

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - metacity --sm-disable --replace &
  - sleep 5

after_success:
  - chmod a+x .travis-deploy.sh
  - "./.travis-deploy.sh"

after_failure:
  - find . -path "*/surefire-reports/*.txt" | xargs cat
