env:
  global:
    - ENCRYPTION_LABEL: "8c7035aad7a2"

install: true

sudo: false

language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

addons:
  apt:
    packages:
      - gnome-themes-standard
      - metacity
      - libwebkit-dev

script:
  - mvn clean verify -q -e -Dtarget-platform-classifier=eclipse-4.5
  - mvn clean verify -q -e -Dtarget-platform-classifier=eclipse-4.6
  - mvn clean verify -q -e -Dtarget-platform-classifier=eclipse-4.7

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - metacity --sm-disable --replace &
  - sleep 5

after_success:
  - chmod a+x .travis-deploy.sh
  - "./.travis-deploy.sh"

after_failure:
  - cat com.codeaffine.extras.ide.test/target/surefire-reports/*.txt
  - cat com.codeaffine.extras.imageviewer.test/target/surefire-reports/*.txt
  - cat com.codeaffine.extras.jdt.test/target/surefire-reports/*.txt
  - cat com.codeaffine.extras.launch.test/target/surefire-reports/*.txt
  - cat com.codeaffine.extras.workingset.test/target/surefire-reports/*.txt
